# Site Settings
title: "Miriam Chun, MSW"
name: "Miriam Chun"
description: "Executive Director @ IRF | PhD Student @ GIST"
url: "https://mirmirchun.github.io"
baseurl: ""
repository: "mirmirchun/mirmirchun.github.io"
remote_theme: "academicpages/academicpages.github.io"

# Sidebar/Author Settings
author:
  avatar: "profile.png" # Make sure your photo is named profile.png in the main folder
  name: "Miriam Chun, MSW"
  bio: "AI Alignment & Global Rehabilitation Equity"
  location: "South Korea"
  employer: "Executive Director @ IRF" <br> "PhD Student @ GIST"
  github: "mirmirchun"
  linkedin: "msw-ai-change"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
